[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
fs_permissions = [{ access = "read", path = "./out" }]

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

[profile.default.fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
base_mainnet = "${BASE_MAINNET_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
ethereum_mainnet = "${ETHEREUM_MAINNET_RPC_URL}"
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"

[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}", chain = 8453 }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532 }
ethereum_mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1 }

[profile.ci]
verbosity = 3
fuzz.runs = 256
optimizer = true
optimizer_runs = 200
via_ir = true
