import { createWalletClient, createPublicClient, http } from 'viem'
import { hashkeyTestnet } from 'viem/chains'
import { privateKeyToAccount } from 'viem/accounts'

// Usage:
//   DEPLOYER_PRIVATE_KEY=0x... node scripts/deploy-hashkey.mjs
//
// After deploy, update .env.local:
//   NEXT_PUBLIC_THIA_TERM_CONTRACT_HASHKEY_TESTNET=<deployed address>
//
// Compile the contract first (requires solc or hardhat):
//   npx solc --abi --bin contracts/ThiaTermPayments.sol -o contracts/out --overwrite
// Then paste the generated bytecode below.

const BYTECODE = process.env.THIA_TERM_BYTECODE
if (!BYTECODE) {
  console.error('Set THIA_TERM_BYTECODE env var with the compiled contract bytecode (0x-prefixed).')
  console.error('Compile with: npx solc --abi --bin contracts/ThiaTermPayments.sol -o contracts/out --overwrite')
  process.exit(1)
}

const PRIVATE_KEY = process.env.DEPLOYER_PRIVATE_KEY
if (!PRIVATE_KEY) {
  console.error('Set DEPLOYER_PRIVATE_KEY env var (0x-prefixed private key with testnet HSK)')
  process.exit(1)
}

const account = privateKeyToAccount(PRIVATE_KEY)

const walletClient = createWalletClient({
  account,
  chain: hashkeyTestnet,
  transport: http('https://hashkeychain-testnet.alt.technology'),
})

const publicClient = createPublicClient({
  chain: hashkeyTestnet,
  transport: http('https://hashkeychain-testnet.alt.technology'),
})

console.log('Deploying ThiaTermPayments from:', account.address)
console.log('Chain: HashKey Testnet (133)')

const hash = await walletClient.deployContract({
  abi: [],
  bytecode: BYTECODE,
})

console.log('Deploy tx:', hash)
const receipt = await publicClient.waitForTransactionReceipt({ hash })
console.log('Contract deployed at:', receipt.contractAddress)
console.log('\nAdd to .env.local:')
console.log('NEXT_PUBLIC_THIA_TERM_CONTRACT_HASHKEY_TESTNET=' + receipt.contractAddress)
